name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
      - name: Set up Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version-file: "pyproject.toml"
      - name: Build package
        run: uv build --no-sources
      - name: Publish package
        run: uv publish --trusted-publishing always
