name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          cache-suffix: "python-${{ matrix.python-version }}"
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --all-extras --dev --python ${{ matrix.python-version }}

      - name: Lint and type-check with prek
        run: uv run prek run --all-files

      - name: Run tests and generate coverage report
        run: uv run pytest --doctest-modules -v --cov=mppt --cov-fail-under 90 --cov-report=term --cov-report=xml --cov-report=html src/mppt tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7.0.0
        if: success() && matrix.os == 'ubuntu-latest' && matrix.python-version == '3.14'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true

      - name: Minimize uv cache
        run: uv cache prune --ci
